import type { Block } from 'payload'
import {
  W1_CAROUSEL_ASPECT_RATIO_TOKENS,
  type W1CarouselAspectRatioToken,
} from '@werk1/w1-system-carouselblock/aspect-ratios'

const aspectRatioLabels: Record<W1CarouselAspectRatioToken, string> = {
  square11: 'Quadrat · 1:1',
  landscape43: 'Querformat · 4:3',
  portrait34: 'Hochformat · 3:4',
  portrait45: 'Hochformat · 4:5',
  landscape169: 'Querformat · 16:9',
  portrait916: 'Hochformat · 9:16',
  wide21: 'Breitformat · 2:1',
}

export const CarouselSectionBlock: Block = {
  slug: 'w1-carousel-block',
  labels: {
    singular: 'Carousel Section',
    plural: 'Carousel Sections',
  },
  fields: [
    {
      name: 'key',
      type: 'text',
      required: true,
      admin: {
        components: {
          Field: '/payload/components/AutoGeneratedKeyField#AutoGeneratedKeyField',
        },
        custom: {
          autoPrefix: 'section',
        },
      },
    },
    {
      name: 'carouselSlug',
      type: 'text',
      admin: {
        components: {
          Field: '/payload/components/SlugSelectField#SlugSelectField',
        },
        custom: {
          sources: [
            { collection: 'carousels', fields: ['slug'], localeMode: 'active' },
          ],
        },
        description: 'Wähle ein Carousel aus der Carousels-Collection',
      },
    },
    {
      name: 'aspectRatio',
      type: 'select',
      required: true,
      defaultValue: 'landscape169',
      label: 'Bildformat',
      options: W1_CAROUSEL_ASPECT_RATIO_TOKENS.map((value) => ({
        label: aspectRatioLabels[value],
        value,
      })),
      admin: {
        description: 'Gemeinsames Seitenverhältnis für alle Karten dieses Carousels.',
      },
    },
    {
      name: 'showImageTitles',
      type: 'checkbox',
      defaultValue: false,
      admin: {
        description: 'Bild-Titel/Dateinamen im Carousel anzeigen',
      },
    },
  ],
}
