import type { Block } from 'payload'

export const ContentSectionBlock: Block = {
  slug: 'w1-content-section',
  labels: {
    singular: 'Content Section',
    plural: 'Content Sections',
  },
  fields: [
    {
      name: 'key',
      type: 'text',
      required: true,
      admin: {
        components: {
          Field: '/payload/components/AutoGeneratedKeyField#AutoGeneratedKeyField',
        },
        custom: {
          autoPrefix: 'section',
        },
      },
    },
    {
      name: 'sectionVariant',
      type: 'select',
      options: [
        { label: 'Default', value: 'default' },
        { label: 'Intro', value: 'intro' },
        { label: 'Hero', value: 'hero' },
        { label: 'Footer', value: 'footer' },
        { label: 'Highlight', value: 'highlight' },
        { label: 'Sidebar', value: 'sidebar' },
      ],
      admin: {
        description: 'Styling variant for the content section. Used as data-variant attribute.',
      },
    },
    {
      name: 'sectionSlug',
      type: 'text',
      admin: {
        components: {
          Field: '/payload/components/SlugSelectField#SlugSelectField',
        },
        custom: {
          sources: [
            { collection: 'text-content', fields: ['identifier'], localeMode: 'active' },
          ],
        },
      },
    },
  ],
}
