import type { Block, Field } from 'payload'
import { FLIPBOOK_SELECT_OPTIONS } from '@/lib/blocks/flipbook/config'

const overrideSelect = (name: keyof typeof FLIPBOOK_SELECT_OPTIONS, label: string): Field => ({
  name,
  label,
  type: 'select',
  options: [...FLIPBOOK_SELECT_OPTIONS[name]],
  admin: { description: 'Leer = Standard des PDF-Dokuments' },
})

const overrideBoolean = (name: string, label: string, description = 'Leer = Standard des PDF-Dokuments'): Field => ({
  name,
  label,
  type: 'select',
  options: [
    { label: 'Ja', value: 'true' },
    { label: 'Nein', value: 'false' },
  ],
  admin: { description },
})

export const FlipbookSectionBlock: Block = {
  slug: 'w1-flipbook-block',
  labels: {
    singular: 'PDF-Viewer Section',
    plural: 'PDF-Viewer Sections',
  },
  fields: [
    {
      name: 'key',
      type: 'text',
      required: true,
      admin: {
        components: {
          Field: '/payload/components/AutoGeneratedKeyField#AutoGeneratedKeyField',
        },
        custom: {
          autoPrefix: 'section',
        },
      },
    },
    {
      name: 'flipbookSlug',
      type: 'text',
      admin: {
        components: {
          Field: '/payload/components/SlugSelectField#SlugSelectField',
        },
        custom: {
          sources: [{ collection: 'flipbooks', fields: ['slug'], localeMode: 'all' }],
        },
        description: 'Wähle ein PDF-Dokument aus der Collection PDF-Dokumente',
      },
    },
    overrideSelect('spreadMode', 'Seitenmodus'),
    overrideSelect('coverMode', 'Cover-Modus'),
    overrideSelect('direction', 'Leserichtung'),
    overrideSelect('theme', 'Theme'),
    overrideSelect('engine', 'Umblätter-Engine'),
    {
      name: 'startPage',
      label: 'Startseite (1-basiert)',
      type: 'number',
      min: 1,
      admin: { description: 'Leer = Standard des PDF-Dokuments' },
    },
    overrideBoolean('showControls', 'Vor/Zurück-Buttons'),
    overrideBoolean('showThumbnails', 'Thumbnails', 'Leer = ausgeblendet (Standard für eingebettete Sections)'),
    {
      name: 'aspectRatio',
      label: 'Seitenverhältnis (CSS)',
      type: 'text',
      admin: { description: 'z. B. 16 / 10. Leer = Standard des PDF-Dokuments' },
    },
    {
      name: 'maxWidthPx',
      label: 'Maximale Breite (px)',
      type: 'number',
      min: 200,
      admin: { description: 'Leer = Standard des PDF-Dokuments' },
    },
  ],
}
