import type { Block } from 'payload'

export const ImageSectionBlock: Block = {
  slug: 'w1-image-block',
  labels: {
    singular: 'Image Section',
    plural: 'Image Sections',
  },
  fields: [
    {
      name: 'key',
      type: 'text',
      required: true,
      admin: {
        components: {
          Field: '/payload/components/AutoGeneratedKeyField#AutoGeneratedKeyField',
        },
        custom: {
          autoPrefix: 'section',
        },
      },
    },
    {
      name: 'mediaSlug',
      type: 'text',
      admin: {
        components: {
          Field: '/payload/components/SlugSelectField#SlugSelectField',
        },
        custom: {
          sources: [
            { collection: 'media', fields: ['slug'], localeMode: 'active', mediaType: 'image' },
          ],
        },
        description: 'Wähle ein Bild aus der Media-Collection',
      },
    },
  ],
}
