import type { Field } from 'payload'

export function createInlineLinkField(autoPrefix: string): Field {
	return {
		name: 'inlineLink',
		type: 'group',
		label: 'Inline Link',
		fields: [
			{
				name: 'key',
				type: 'text',
				admin: {
					components: {
						Field: '/payload/components/AutoGeneratedKeyField#AutoGeneratedKeyField',
					},
					custom: {
						autoPrefix,
					},
					description: 'Eindeutiger Anker für Inline-Menüs innerhalb des Artikels.',
				},
			},
			{
				name: 'label',
				type: 'text',
				admin: {
					description: 'Anzeigetext für Menüs oder Inline-Navigation.',
				},
			},
		],
	}
}
