'use client'

import { TextInput, useField } from '@payloadcms/ui'
import { useEffect, useMemo, useRef } from 'react'
import type { ChangeEvent } from 'react'
import type { TextFieldClientComponent } from 'payload'

function makeRandomToken(length: number): string {
  return Math.random().toString(36).slice(2, 2 + length)
}

function normalizeKey(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
}

function generateKey(prefix: string): string {
  const normalizedPrefix = normalizeKey(prefix) || 'item'
  const randomPart = makeRandomToken(8)
  return `${normalizedPrefix}-${randomPart}`
}

export const AutoGeneratedKeyField: TextFieldClientComponent = ({ field, path }) => {
  const { value, setValue } = useField<string>({ path })
  const initializedRef = useRef(false)

  const prefix = useMemo(() => {
    const custom = (field.admin?.custom ?? {}) as { autoPrefix?: string }
    return custom.autoPrefix ?? field.name ?? 'item'
  }, [field.admin?.custom, field.name])

  useEffect(() => {
    if (initializedRef.current) return

    const currentValue = typeof value === 'string' ? value.trim() : ''
    if (currentValue.length > 0) {
      initializedRef.current = true
      return
    }

    initializedRef.current = true
    setValue(generateKey(prefix))
  }, [prefix, setValue, value])

  return (
    <TextInput
      path={path}
      label={field.label}
      required={field.required}
      value={typeof value === 'string' ? value : ''}
      onChange={(event: ChangeEvent<HTMLInputElement>) => setValue(event.target.value)}
      description={field.admin?.description}
    />
  )
}
